version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net: